var CONFIG = {
  CALENDAR_ID: 'miyago.shigotono@gmail.com',
  TIMEZONE: 'Asia/Tokyo',
  DAYOFF_TITLE: '休み',
  DEFAULT_EVENT_DURATION_MIN: 60,
  BLOCK_PADDING_DAYS: 14,
  MAX_QUERY_SPAN_DAYS: 120,
  FREE_WINDOW_START_HOUR: 18,
  FREE_WINDOW_END_HOUR: 22
};
